version: "3.8"

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    container_name: vr-desafio-api
    ports:
      - "3000:3000"
    volumes:
      - ./api:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - RABBITMQ_URL=amqp://rabbitmq:5672
    depends_on:
      - rabbitmq
    networks:
      - vr-network
    restart: unless-stopped

  web:
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    container_name: vr-desafio-web
    ports:
      - "4200:4200"
    volumes:
      - ./web:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - API_URL=http://api:3000
    depends_on:
      - api
    networks:
      - vr-network
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: vr-desafio-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin123
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - vr-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  rabbitmq_data:
    driver: local

networks:
  vr-network:
    driver: bridge
